baseURL = 'https://mscharley.github.io/dot/'
languageCode = 'en-us'
title = 'DOT'
# Will give values to .Lastmod etc.
enableGitInfo = true

[markup]
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true

[params]
# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/mscharley/dot"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/mscharley/dot"
# Specify a value here if your content directory is not in your repo's root directory
github_subdir = "docs"

[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 100

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[security.exec]
osEnv = [
	# This is the default value.
	'(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM)$',
	# Allow ASDF variables as well
	'^ASDF_',
]
