import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// eslint-disable-next-line @typescript-eslint/no-type-alias
export type DotSidebars = 'docsSidebar';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: Record<DotSidebars, SidebarsConfig[string]> = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	docsSidebar: [{ type: 'autogenerated', dirName: '.' }],

	// But you can create a sidebar manually
	/*
	tutorialSidebar: [
		'intro',
		'hello',
		{
			type: 'category',
			label: 'Tutorial',
			items: ['tutorial-basics/create-a-document'],
		},
	],
	/* */
} satisfies SidebarsConfig;

export default sidebars;
