name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    uses: mscharley/.github/.github/workflows/changesets.yml@64a755d02d9fa9ab9f4d0e134c8379c57f2c32fe # main
    with:
      node-version-file: .tool-versions
    permissions:
      contents: write
      id-token: write
    secrets:
      token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}
      npm-token: ${{ secrets.NPM_TOKEN }}
