# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  node:
    uses: mscharley/.github/.github/workflows/node-ci.yml@3ea5efb827af3ad6391fa1a055197cea50931c25 # main
    permissions: {}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x, current]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    with:
      node-version: ${{ matrix.node-version }}

  docs:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Hugo CLI
        run: |
          HUGO_VERSION="$(grep '^hugo ' .tool-versions | awk 'BEGIN { FS="_" } { print $2 }')"
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .tool-versions
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build docs
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: pnpx turbo build:docs

  stryker:
    uses: mscharley/.github/.github/workflows/stryker.yml@3ea5efb827af3ad6391fa1a055197cea50931c25 # main
    permissions: {}
