name: Add changeset to Renovate updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  update:
    uses: mscharley/.github/.github/workflows/renovate-changesets.yml@64a755d02d9fa9ab9f4d0e134c8379c57f2c32fe # main
    permissions: {}
    secrets:
      token: ${{ secrets.DEPENDENCY_UPDATE_GITHUB_TOKEN }}
