name: Add changeset to Renovate updates

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  update:
    name: Update Renovate PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    permissions:
      contents: write

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-semantic-commits: false
