name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  stale:
    uses: mscharley/.github/.github/workflows/stale.yml@64a755d02d9fa9ab9f4d0e134c8379c57f2c32fe # main
    permissions:
      issues: write
      pull-requests: write
      discussions: write
